package groups

import (
	"fmt"
	"sort"
	"strings"

	"github.com/muthuishere/aos/internal/cli"
)

func init() {
	register(func(r *cli.Registry) {
		r.Describe("completion", "Shell tab-completion for aos")
		r.Add(&cli.Command{
			Group:   "completion",
			Summary: "Print a shell completion script generated from the command tree",
			Args:    "<bash|zsh|fish>",
			Examples: []string{
				"aos completion bash",
				"aos completion zsh",
				"aos completion fish",
			},
			Run: runCompletion,
		})
	})
}

func runCompletion(c *cli.Ctx, args []string) error {
	set, err := parseArgs(args)
	if err != nil {
		return err
	}
	if err := set.Reject(); err != nil {
		return err
	}
	if len(set.Rest) != 1 {
		return &cli.ExitError{Code: 1, Message: "usage: aos completion <bash|zsh|fish>"}
	}

	shell := set.Rest[0]
	script, err := completionScript(c.Registry, shell)
	if err != nil {
		return &cli.ExitError{Code: 1, Message: err.Error()}
	}
	c.Printf("%s", script)
	return nil
}

// completionNode is one point in the command tree: everything that may legally
// follow `aos <key>`. The key is the space-joined route prefix, empty at the
// root, so a multi-token route such as `audio output set default` contributes
// one node per word rather than being flattened.
type completionNode struct {
	Key   string
	Words []string
}

// completionTree walks the registry and returns its nodes, sorted by key, with
// each node's words sorted. Generating from the registry is the whole point:
// the script cannot describe commands that do not exist.
func completionTree(reg *cli.Registry) []completionNode {
	children := map[string]map[string]bool{}
	add := func(prefix, word string) {
		if !safeCompletionWord(word) {
			return
		}
		if children[prefix] == nil {
			children[prefix] = map[string]bool{}
		}
		children[prefix][word] = true
	}

	// `commands` is handled by dispatch rather than the registry, so it has to
	// be named here or completion would quietly forget a top-level command.
	add("", "commands")
	for _, flag := range []string{"--all", "--json", "--check"} {
		add("commands", flag)
	}

	for _, g := range reg.Groups() {
		for _, cmd := range g.Commands {
			if cmd.Hidden || !cmd.Available() {
				continue
			}
			add("", g.Name)
			break
		}
	}

	for _, cmd := range reg.Commands() {
		if cmd.Hidden || !cmd.Available() {
			continue
		}
		words := strings.Fields(cmd.Route())
		for i, word := range words {
			add(strings.Join(words[:i], " "), word)
		}
		route := strings.Join(words, " ")
		for _, flag := range completionFlags(cmd.Args) {
			add(route, flag)
		}
	}

	keys := make([]string, 0, len(children))
	for key := range children {
		keys = append(keys, key)
	}
	sort.Strings(keys)

	nodes := make([]completionNode, 0, len(keys))
	for _, key := range keys {
		words := make([]string, 0, len(children[key]))
		for word := range children[key] {
			words = append(words, word)
		}
		sort.Strings(words)
		nodes = append(nodes, completionNode{Key: key, Words: words})
	}
	return nodes
}

// completionFlags pulls the flag names out of an Args string such as
// `[--json] [--app=<name>] <path>`. The declared usage line is the only place a
// command documents its flags, so it is also the only honest source here.
func completionFlags(args string) []string {
	var out []string
	seen := map[string]bool{}
	for i := 0; i+1 < len(args); i++ {
		if args[i] != '-' || args[i+1] != '-' {
			continue
		}
		if i > 0 && isFlagRune(args[i-1]) {
			continue
		}
		end := i + 2
		for end < len(args) && isFlagRune(args[end]) {
			end++
		}
		name := args[i:end]
		if len(name) > 2 && !seen[name] {
			seen[name] = true
			out = append(out, name)
		}
		i = end - 1
	}
	sort.Strings(out)
	return out
}

func isFlagRune(b byte) bool {
	switch {
	case b >= 'a' && b <= 'z', b >= 'A' && b <= 'Z', b >= '0' && b <= '9':
		return true
	case b == '-', b == '_':
		return true
	}
	return false
}

// safeCompletionWord keeps anything odd out of the generated script. Every real
// route word and flag is plain ASCII, so this only ever drops something that
// would have broken the shell it was embedded in.
func safeCompletionWord(word string) bool {
	if word == "" {
		return false
	}
	for i := 0; i < len(word); i++ {
		b := word[i]
		if isFlagRune(b) || b == '.' || b == ':' || b == '+' || b == '@' {
			continue
		}
		return false
	}
	return true
}

func completionScript(reg *cli.Registry, shell string) (string, error) {
	nodes := completionTree(reg)
	switch shell {
	case "bash":
		return bashCompletion(nodes), nil
	case "zsh":
		return zshCompletion(nodes), nil
	case "fish":
		return fishCompletion(nodes), nil
	default:
		return "", fmt.Errorf("unknown shell %q: want bash, zsh, or fish", shell)
	}
}

const completionBanner = "# aos shell completion — generated by `aos completion`, do not edit.\n"

func bashCompletion(nodes []completionNode) string {
	var b strings.Builder
	b.WriteString(completionBanner)
	b.WriteString("# Install with: aos completion bash > /etc/bash_completion.d/aos\n\n")
	b.WriteString("_aos_complete() {\n")
	b.WriteString("    local cur prefix word choices i\n")
	b.WriteString("    COMPREPLY=()\n")
	b.WriteString("    cur=\"${COMP_WORDS[COMP_CWORD]}\"\n")
	b.WriteString("    prefix=\"\"\n")
	b.WriteString("    for ((i = 1; i < COMP_CWORD; i++)); do\n")
	b.WriteString("        word=\"${COMP_WORDS[i]}\"\n")
	b.WriteString("        case \"$word\" in -*) continue ;; esac\n")
	b.WriteString("        if [ -z \"$prefix\" ]; then prefix=\"$word\"; else prefix=\"$prefix $word\"; fi\n")
	b.WriteString("    done\n")
	b.WriteString("    case \"$prefix\" in\n")
	for _, node := range nodes {
		fmt.Fprintf(&b, "        '%s') choices='%s' ;;\n", node.Key, strings.Join(node.Words, " "))
	}
	b.WriteString("        *) choices='' ;;\n")
	b.WriteString("    esac\n")
	b.WriteString("    COMPREPLY=($(compgen -W \"$choices\" -- \"$cur\"))\n")
	b.WriteString("}\n")
	b.WriteString("complete -F _aos_complete aos\n")
	return b.String()
}

func zshCompletion(nodes []completionNode) string {
	var b strings.Builder
	b.WriteString("#compdef aos\n")
	b.WriteString(completionBanner)
	b.WriteString("# Install with: aos completion zsh > \"${fpath[1]}/_aos\"\n\n")
	b.WriteString("_aos() {\n")
	b.WriteString("    local prefix=\"\" word choices i\n")
	b.WriteString("    for (( i = 2; i < CURRENT; i++ )); do\n")
	b.WriteString("        word=\"${words[i]}\"\n")
	b.WriteString("        case \"$word\" in (-*) continue ;; esac\n")
	b.WriteString("        if [[ -z \"$prefix\" ]]; then prefix=\"$word\"; else prefix=\"$prefix $word\"; fi\n")
	b.WriteString("    done\n")
	b.WriteString("    case \"$prefix\" in\n")
	for _, node := range nodes {
		fmt.Fprintf(&b, "        ('%s') choices='%s' ;;\n", node.Key, strings.Join(node.Words, " "))
	}
	b.WriteString("        (*) choices='' ;;\n")
	b.WriteString("    esac\n")
	b.WriteString("    compadd -- ${=choices}\n")
	b.WriteString("}\n")
	// Sourced (`source <(aos completion zsh)`) the function has to be registered;
	// autoloaded from fpath the file itself IS the completion function and must
	// run instead. One check covers both installs.
	b.WriteString("if [ \"${funcstack[1]}\" = \"_aos\" ]; then\n")
	b.WriteString("    _aos \"$@\"\n")
	b.WriteString("else\n")
	b.WriteString("    compdef _aos aos\n")
	b.WriteString("fi\n")
	return b.String()
}

func fishCompletion(nodes []completionNode) string {
	var b strings.Builder
	b.WriteString(completionBanner)
	b.WriteString("# Install with: aos completion fish > ~/.config/fish/completions/aos.fish\n\n")
	// Fish has no notion of a route prefix, so the helper rebuilds one from the
	// tokens typed so far — flags dropped, exactly as bash and zsh do.
	b.WriteString("function __aos_at --argument-names expect\n")
	b.WriteString("    set -l tokens (commandline -opc)\n")
	b.WriteString("    set -l route\n")
	b.WriteString("    set -e tokens[1]\n")
	b.WriteString("    for token in $tokens\n")
	b.WriteString("        if string match -q -- '-*' $token\n")
	b.WriteString("            continue\n")
	b.WriteString("        end\n")
	b.WriteString("        set -a route $token\n")
	b.WriteString("    end\n")
	b.WriteString("    set -l prefix (string join ' ' $route)\n")
	b.WriteString("    test \"$prefix\" = \"$expect\"\n")
	b.WriteString("end\n\n")
	b.WriteString("complete -c aos -f\n")
	for _, node := range nodes {
		fmt.Fprintf(&b, "complete -c aos -f -n '__aos_at \"%s\"' -a '%s'\n",
			node.Key, strings.Join(node.Words, " "))
	}
	return b.String()
}
